/*
 * This file is part of Jehanne.
 *
 * Copyright (C) 2017 Giacomo Tesio <giacomo@tesio.it>
 *
 * Jehanne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 2 of the License.
 *
 * Jehanne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jehanne.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Lib9.c can be included in plan9 programs to provide functions that
 * are expected by autogenerated code (eg via yacc)
 */

#include <u.h>
#include <libc.h>

void*
memcpy(void* a, const void* b, size_t c)
{
	return jehanne_memcpy(a,b,c);
}

void*
malloc(size_t s)
{
	return jehanne_malloc(s);
}

void
free(void* p)
{
	return jehanne_free(p);
}
